n = input('Digite algo:')
print('O tipo primitivo é {} '.format(type(n)))
print('Tem apenas letras? {} '.format(n.isalpha()))
print('Tem apenas números? {} '.format(n.isnumeric()))
print('Tem letras ou números? {} '.format(n.isalnum()))
print('Tem letras apenas letras maiúsculas? {} '.format(n.isupper()))
print('Tem digitos? {} '.format(n.isdigit()))
print('É decimal? {}  '.format(n.isdecimal()))
print('Possui apenas letras minúsculas? {} '.format(n.islower()))
print('É composto apenas de espaços? {} '.format(n.isspace()))
print('É possível imprimir? {} '.format(n.isprintable()))
print('Está capitalizado? {} '.format(n.istitle()))
